version: '3.8'
services:
  reverse-proxy:
    restart: always
    image: traefik
    container_name: reverse-proxy
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config/traefik/:/etc/traefik/"
      - "./certs:/etc/certs/"
    labels:
      # HTTP
      - "traefik.http.routers.dashboard-http.rule=Host(`traefik.local`)"
      - "traefik.http.routers.dashboard-http.entrypoints=web"
      # HTTPS
      - "traefik.http.routers.dashboard-https.rule=Host(`traefik.local`)"
      - "traefik.http.routers.dashboard-https.entrypoints=websecure"
      - "traefik.http.routers.dashboard-https.tls=true"      
       # API
      - "traefik.http.routers.dashboard-http.service=api@internal"
      - "traefik.http.routers.dashboard-https.service=api@internal"
      # AUTH
      - "traefik.http.routers.dashboard-http.middlewares=dashboard-auth"
      - "traefik.http.routers.dashboard-https.middlewares=dashboard-auth"
      - "traefik.http.middlewares.dashboard-auth.basicauth.users={{ user:password }}"
    networks:
      - web

  registry-ui:
    image: joxit/docker-registry-ui:main
    restart: always
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Docker Registry UI
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://registry-server:5000
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=false
      - CATALOG_ELEMENTS_LIMIT=1000
    container_name: registry-ui
    labels:
      # HTTP
      - "traefik.http.routers.registry-ui-http.rule=Host(`registry-ui.local`)"
      - "traefik.http.routers.registry-ui-http.entrypoints=web"
      # HTTPS
      - "traefik.http.routers.registry-ui-https.rule=Host(`registry-ui.local`)"
      - "traefik.http.routers.registry-ui-https.entrypoints=websecure"
      - "traefik.http.routers.registry-ui-https.tls=true"      
      # AUTH
      - "traefik.http.routers.registry-ui-http.middlewares=registry-ui-auth"
      - "traefik.http.routers.registry-ui-https.middlewares=registry-ui-auth"
      - "traefik.http.middlewares.registry-ui-auth.basicauth.users={{ user:password }}"
    networks:
      - web

  registry-server:
    image: registry:2.8.2
    restart: always
    environment:
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin: '[http://registry.example.com]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods: '[HEAD,GET,OPTIONS,DELETE]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials: '[true]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers: '[Authorization,Accept,Cache-Control]'
      REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers: '[Docker-Content-Digest]'
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'

    volumes:
      - ./registry/data:/var/lib/registry
    container_name: registry-server
    labels:
      # HTTP
      - "traefik.http.routers.registry-http.rule=Host(`registry.local`)"
      - "traefik.http.routers.registry-http.entrypoints=web"
      # HTTPS
      - "traefik.http.routers.registry-https.rule=Host(`registry.local`)"
      - "traefik.http.routers.registry-https.entrypoints=websecure"
      - "traefik.http.routers.registry-https.tls=true"      
    networks:
      - web

networks:
  web:
    external: true
  internal:
    external: false